---
deployment:
  tasks:
    - export DEPLOYPATH=/home/webinertia/aurora/
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R data $DEPLOYPATH
    - /bin/cp -R languages $DEPLOYPATH
    - /bin/cp -R module $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
---